language: php

env:
  - BYTIC_VERSION=^1.0

matrix:
  include:
    - php: 7.4
      env: BYTIC_VERSION=^1.0

install:
  - composer update --prefer-source --no-interaction --dev

before_install:
  - composer require "bytic/orm:${BYTIC_VERSION}" --no-update

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml